#!/usr/bin/env ansible-playbook
---
# This playbook will upgrade kubernetes version on nodes
#
- hosts: localhost
  remote_user: username
  become: yes
  become_method: sudo

  tasks:
    - name: Get latest RKE release information
      uri:
        url: https://api.github.com/repos/rancher/rke/releases/latest
        return_content: yes
      register: rke_release_info

    - name: Find RKE amd64 Linux binary asset
      set_fact:
        rke_amd64_linux_asset: "{{ item }}"
      loop: "{{ rke_release_info.json.assets }}"
      when: "'amd64' in item.name and 'linux' in item.name and item.content_type == 'application/octet-stream'"

    - name: Set RKE download URL and latest Kubernetes version
      set_fact:
        rke_download_url: "{{ rke_amd64_linux_asset.browser_download_url }}"
        rke_kubernetes_version: "{{ rke_release_info.json.name }}"

    - name: Download the latest RKE binary
      get_url:
        url: "{{ rke_download_url }}"
        dest: "/usr/local/bin/rke"
        mode: '0755'

    - name: "Check out latest kubernetes verion"
      shell: rke config --list-version --all | sort | tail -n 1
      register: kubernetes

    - name: "Add newest kubernets version to cluster.yml config file"
      lineinfile:
        path: /kvm/cluster.yml
        regexp: '^kubernetes_version'
        line: "kubernetes_version: {{ kubernetes.stdout }}"

    - name: "Upgrade kubernetes version"
      shell: rke up --config /kvm/cluster.yml
      become_user: username
